### ISSUE TITLE
Only works for single-value declarations

### ISSUE THREAD

**Issue by davidtheclark** [himynameisdave/postcss-round-subpixels#1]
For example, the plugin will currently turn `padding: 15.24px 20.34px;` into `padding: 15px;`.

I think that this plugin could be made much more robust by using https://github.com/TrySound/postcss-value-parser. Are you open to a PR to try that out and add more tests?

**Comment by himynameisdave** [comment]
@davidtheclark thanks & I totally agree, will absolutely be using  `postcss-value-parser` here!
