### ISSUE TITLE
Can you optimize opacity calculation?

### ISSUE THREAD

**Issue by denisx** [himynameisdave/postcss-round-subpixels#4]
<img width="364" alt="Screenshot 2019-04-24 at 12 21 31" src="https://user-images.githubusercontent.com/427776/56649002-f8f87d80-668c-11e9-8587-feaa9984daba.png">

**Comment by himynameisdave** [comment]
@denisx this seems a bit out-of-scope for this plugin, but perhaps a new plugin could handle this!
