### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [himynameisdave/postcss-round-subpixels#5]
**Thanks for your PostCSS plugin!** 

As you probably know, [PostCSS 8] was released a few days ago. It would be great if you could make this plugin compatible with the latest version. The creators of the project have even released this [migration guide].

[PostCSS 8]: https://github.com/postcss/postcss/releases/tag/8.0.0
[migration guide]: https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by himynameisdave** [comment]
@jonnitto didn't know anyone still used this plugin! I am a bit busy but will get to this when I have some bandwidth. Feel free to open a PR if it is a serious blocker for you and I will merge it quickly!

**Comment by louh** [comment]
We're using it over at https://github.com/streetmix/streetmix! 

This is not a huge blocker for us, as it's more of a quality-of-life visual thing, but I also wanted to thank you for making this package and let you know you do have users!

**Comment by himynameisdave** [comment]
Ask and ye shall receive: https://github.com/himynameisdave/postcss-round-subpixels/releases/tag/v2.0.0

Happy holidays, and thanks @louh && @jonnitto for letting me know this old plugin is still being used! 👍 💯

**Comment by louh** [comment]
Nice, thank you so much!
